oxideeRepository: http://myhost/development/oxid/ee
sRewriteBase: /
remoteDbName: oxid
remoteDbUser: oxid-readonly
remoteDbPwd: secret password
remotePath: /srv/www/oxid
dbHost: localhost
dbName: oxid
dbUser: oxid
dbPwd: secret password
mysql_password: secret password
sShopDir: /srv/www/oxid
sCompileDir: /srv/www/oxid/tmp
sTheme: basic
iUtfMode: 0